server:
  servlet:
    context-path: /system
  port: 63110
#微服务配置
spring:
  application:
    name: system-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.101.65:3306/xcgsy_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
    url: jdbc:mysql://localhost:3306/xcgsy_system?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
    username: root
    #    password: mysql
    password: 123456


# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml

